### PR TITLE
feat: adds more quotes in the data collection

### LINKED ISSUE #1: Add more quotes and Writer's name
### Add more number of quote along with the writer's name

### PR DESCRIPTION
**Pull request by wsameer**
fixes #1

### CODE REVIEW

**Review by ZiaCodes — CHANGES_REQUESTED** [review]
#3

**Comment by wsameer** [comment]
> #3 please add more number of quote at least 20

added 36 quotes! Let me know if you want more.

Also, it would help me a lot if you add "hacktoberfest-accepted" label to this PR. TIA.

**Review by ZiaCodes — CHANGES_REQUESTED** [review]
@wsameer @t29 writers are missing .
please add those relevant writer's name

**Comment by wsameer** [comment]
> @wsameer @t29 writers are missing . please add those relevant writer's name

The issue title doesn't mention anything about authors. If you want that, then create a new issue and I'd be happy to take that up.

**Comment by ZiaCodes** [comment]
> > @wsameer @t29 writers are missing . please add those relevant writer's name
> 
> The issue title doesn't mention anything about authors. If you want that, then create a new issue and I'd be happy to take that up.

Do the writer's Name

**Comment by wsameer** [comment]
> > > @wsameer @t29 writers are missing . please add those relevant writer's name
> > 
> > 
> > The issue title doesn't mention anything about authors. If you want that, then create a new issue and I'd be happy to take that up.
> 
> Do the writer's Name

done.

**Review by ZiaCodes — APPROVED** [review]
#1

**Comment by ZiaCodes** [comment]
@wsameer Great Job

**Comment by wsameer** [comment]
@ZiaCodes  can you add "hacktoberfest" (all small case) to the topic of the repo. 
As per the official website, this repository is not participating in this years hacktoberfest.

**Comment by ZiaCodes** [comment]
@wsameer sure

**Pull request merged**
